👌IMPROVE: PHPCS Test
ahmadbilaldev/SOP-Highlighter pull request #4
Opened 2020-03-22 15:52 UTC by ahmadbilaldev

2020-03-22 16:11 UTC, ahmadbilaldev commented
GitHub API communication error. Please contact a human. (commit-ID: 2ab3e860159a5cb2d0d8f4d729f3dd320ac85c1c).

2020-03-23 08:09 UTC, theprismane requested changes
**phpcs** scanning turned up:

:no_entry_sign: 17 errors 

:warning: 6 warnings 

***

**hashes-api**-scanning skipped


Posting will continue in further review(s)

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
> +	// Test PHPCS check, should give warning for this comment
:no_entry_sign: **Error**: Inline comments must end in full-stops, exclamation marks, or question marks (*Squiz.Commenting.InlineComment.InvalidEndChar*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"yaml" => "YAML",
:no_entry_sign: **Error**: String &quot;YAML&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"yaml" => "YAML",
:warning: **Warning**: Array double arrow not aligned correctly; expected 7 space(s) between &quot;&quot;yaml&quot;&quot; and double arrow, but found 1 (*WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"yaml" => "YAML",
:no_entry_sign: **Error**: String &quot;yaml&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"xml" => "XML",
:no_entry_sign: **Error**: String &quot;XML&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"xml" => "XML",
:warning: **Warning**: Array double arrow not aligned correctly; expected 8 space(s) between &quot;&quot;xml&quot;&quot; and double arrow, but found 1 (*WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"xml" => "XML",
:no_entry_sign: **Error**: String &quot;xml&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"wiki" => "Wiki markup",
:no_entry_sign: **Error**: String &quot;Wiki markup&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"wiki" => "Wiki markup",
:warning: **Warning**: Array double arrow not aligned correctly; expected 7 space(s) between &quot;&quot;wiki&quot;&quot; and double arrow, but found 1 (*WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"wiki" => "Wiki markup",
:no_entry_sign: **Error**: String &quot;wiki&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane requested changes
Previous scan continued.

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"vim" => "vim",
:warning: **Warning**: Array double arrow not aligned correctly; expected 8 space(s) between &quot;&quot;vim&quot;&quot; and double arrow, but found 1 (*WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"vim" => "vim",
:no_entry_sign: **Error**: String &quot;vim&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"typescript" => "TypeScript",
:no_entry_sign: **Error**: String &quot;TypeScript&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"typescript" => "TypeScript",
:no_entry_sign: **Error**: String &quot;typescript&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"toml" => "TOML",
:no_entry_sign: **Error**: String &quot;TOML&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"toml" => "TOML",
:warning: **Warning**: Array double arrow not aligned correctly; expected 7 space(s) between &quot;&quot;toml&quot;&quot; and double arrow, but found 1 (*WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"toml" => "TOML",
:no_entry_sign: **Error**: String &quot;toml&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"bash" => "Bash/Shell",
:no_entry_sign: **Error**: String &quot;Bash/Shell&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"bash" => "Bash/Shell",
:warning: **Warning**: Array double arrow not aligned correctly; expected 7 space(s) between &quot;&quot;bash&quot;&quot; and double arrow, but found 1 (*WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"bash" => "Bash/Shell",
:no_entry_sign: **Error**: String &quot;bash&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane requested changes
Previous scan continued.

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"apacheconf" => "Apache Config",
:no_entry_sign: **Error**: String &quot;Apache Config&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>  		"apacheconf" => "Apache Config",
:no_entry_sign: **Error**: String &quot;apacheconf&quot; does not require double quotes; use single quotes instead (*Squiz.Strings.DoubleQuoteUsage.NotRequired*).

2020-03-23 08:09 UTC, theprismane commented on prism-languages.php
>   * @return array Hash of lang => language
:no_entry_sign: **Error**: There must be exactly one blank line before the tags in a doc comment (*Generic.Commenting.DocComment.SpacingBeforeTags*).

2020-03-27 16:16 UTC, closed without merging